apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-config
  namespace: bluegreen
data:
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_NAME: "{{ .Values.database.name }}"
