apiVersion: apps/v1
kind: Deployment

metadata:
  name: bluegreen-app-green
  namespace: bluegreen
  labels:
    app: bluegreen-app
    version: green

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bluegreen-app
      version: green

  template:
    metadata:
      labels:
        app: bluegreen-app
        version: green

    spec:
      containers:
        - name: bluegreen-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: DB_PASSWORD
