apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: bluegreen
type: Opaque
stringData:
  DB_USERNAME: "{{ .Values.database.username }}"
  DB_PASSWORD: "{{ .Values.database.password }}"
